#! /usr/bin/env python

# kanet binary
obj = bld(
	features = 'cc cshlib',
	packages = 'KanetAuthModule gmodule-2.0 glib-2.0 ',
	uselib = 'GLIB',
	includes = '../../include',
	#uselib_local = 'KanetAuthModule',
	target = 'kanet-dummy',
	vapi_dirs='../../vapi/ .'
	)

obj.find_sources_in_dirs('.')

