/* KanetAuthModule.vapi generated by valac, do not modify. */

[CCode (cheader_filename = "KanetAuthModule.h")]
public interface KanetAuthModule : GLib.Object {
	public abstract bool check_auth (string login, string password, string domain, string ip, out uint8 group_mark);
}
