#! /usr/bin/env python

# kanet binary
obj = bld(
	features = 'cc cshlib',
	packages = 'KanetAuthModule nss-ldap gee-1.0 gmodule-2.0 glib-2.0 ',
	uselib = 'nss-ldap GLIB',
	includes = '../../include',
	#uselib_local = 'KanetAuthModule',
	target = 'kanet-ldap',
	vapi_dirs='../../vapi/ .'
	)

obj.find_sources_in_dirs('.')

