/* KanetAuthModule.h generated by valac, the Vala compiler, do not modify */


#ifndef __DEFAULT_SRC_KANETAUTHMODULE_H__
#define __DEFAULT_SRC_KANETAUTHMODULE_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TYPE_KANET_AUTH_MODULE (kanet_auth_module_get_type ())
#define KANET_AUTH_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_KANET_AUTH_MODULE, KanetAuthModule))
#define IS_KANET_AUTH_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_KANET_AUTH_MODULE))
#define KANET_AUTH_MODULE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_KANET_AUTH_MODULE, KanetAuthModuleIface))

typedef struct _KanetAuthModule KanetAuthModule;
typedef struct _KanetAuthModuleIface KanetAuthModuleIface;

struct _KanetAuthModuleIface {
	GTypeInterface parent_iface;
	gboolean (*check_auth) (KanetAuthModule* self, const char* login, const char* password, const char* domain, const char* ip, guint8* group_mark);
};


GType kanet_auth_module_get_type (void);
gboolean kanet_auth_module_check_auth (KanetAuthModule* self, const char* login, const char* password, const char* domain, const char* ip, guint8* group_mark);


G_END_DECLS

#endif
