#! /usr/bin/env python
# encoding: utf-8
import Options

# kanet binary
obj = bld(
	features = 'cc cprogram',
	packages = 'Config kanetnetfilter gee-1.0 gmodule-2.0 json-glib-1.0 gnet-2.0 glib-2.0 libsoup-2.4 sqlite3 posix libdaemon mysql',
	uselib = 'netfilter_conntrack netfilter_queue GLIB GMODULE GEE JSON GNET GLIB LIBSOUP SQLITE3 MYSQL POSIX GTHREAD DAEMON',
	target = 'kanet',
	vapi_dirs='.',
	threading=True
	)

#obj.source='vala-gtk-example.vala'
obj.find_sources_in_dirs('.') # take the sources in the current folderbld.add_subdirs ('util')

if Options.options.debug:
  obj.env = bld.env_of_name ('debug').copy ()

# auth module library
lib = bld(
	features = 'cc cshlib',
	packages = 'gmodule-2.0 glib-2.0',
	uselib = 'GLIB GMODULE ',
	source='KanetAuthModule.vala',
	target='KanetAuthModule'
	)

bld.add_subdirs ('RadiusAuthModule')
bld.add_subdirs ('DummyAuthModule')
