#! /usr/bin/env python
# encoding: utf-8

bld.program(
        packages      = 'Config kanetnetfilter gee-1.0 gmodule-2.0 json-glib-1.0 gnet-2.0 glib-2.0 libsoup-2.4 sqlite3 posix libdaemon',
        target        = 'kanet',
        uselib        = 'netfilter_conntrack netfilter_queue GLIB GMODULE GEE JSON GNET GLIB LIBSOUP SQLITE3 POSIX GTHREAD DAEMON',
        source        = 'main.vala Acl.vala BlacklistUser.vala Configuration.vala KanetApplication.vala KBaseSqlite.vala KBase.vala Log.vala Session.vala  User.vala Utils.vala  WebServers.vala KanetAuthModule.vala kanetnetfilter.c',
	vapi_dirs='../vapi/ .',
	includes = '../include/',
        vala_defines  = ['DEBUG']
        )

bld.program(
        packages      = 'Config kanetnetfilter gee-1.0 gmodule-2.0 json-glib-1.0 gnet-2.0 glib-2.0 sqlite3 posix curses',
        target        = 'kanet-acl',
        uselib        = 'ncurses GLIB GMODULE GEE JSON GNET GLIB SQLITE3',
        source        = 'kanet-acl.vala Acl.vala BlacklistUser.vala Configuration.vala KBaseSqlite.vala KBase.vala Log.vala Session.vala  User.vala Utils.vala',
	vapi_dirs='../vapi/ .',
	includes = '../include/',
        vala_defines  = ['DEBUG']
        )
