#! /usr/bin/env python

# kanet binary
obj = bld(
	features = 'cc cshlib',
	packages = 'KanetAuthModule radiusclient gee-1.0 gmodule-2.0 glib-2.0 ',
	uselib = 'radiusclient-ng GLIB',
	includes = '../../include',
	#uselib_local = 'KanetAuthModule',
	target = 'kanet-radiusclient',
	vapi_dirs='../../vapi/ .'
	)

obj.find_sources_in_dirs('.')

